---
title: "TCGA-BRCA Gene Expression Analysis with bregr"
author: 
  - name: Shixiang Wang
    affiliation: Central South University
    email: wangshx@csu.edu.cn
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{TCGA-BRCA Gene Expression Analysis with bregr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

```{r setup}
#remotes::install_github("wanglabcsu/bregr", dependencies = TRUE)

library(bregr)
library(UCSCXenaTools)
library(UCSCXenaShiny)
```

## Download Data

```{r}
XenaGenerate() |>
  XenaFilter(filterDatasets = "TCGA.BRCA.sampleMap/HiSeqV2_PANCAN")
```

```{r eval=FALSE}
XenaGenerate() |>
  XenaFilter(filterDatasets = "TCGA.BRCA.sampleMap/HiSeqV2_PANCAN") |> 
  XenaQuery() |> 
  XenaDownload(destdir = "")
```

## Preprocessing Data

```{r}
data = XenaPrepare("HiSeqV2_PANCAN.gz")
head(data[, 1:10])
```

Firstly, we need to convert genes to columns.

```{r}
data_t = tidyr::pivot_longer(data, cols = colnames(data)[-1]) |> 
  tidyr::pivot_wider(id_cols = "name", names_from = "sample", values_from = "value", values_fill = NA_real_)
head(data_t[, 1:10])
```

Next join the overall survival data.

```{r}
data2 = dplyr::inner_join(
  tcga_surv |> dplyr::select(sample, OS, OS.time) |> 
    dplyr::filter(!is.na(OS), !is.na(OS.time)),
  data_t, by = c("sample" = "name")
)
head(data2[, 1:10])
```

So we next run **bregr** with `r nrow(data2)` samples, `r ncol(data2)-3` variables.

## Execute bregr Pipeline

```{r}
gene_names = names(data_t)[-1]

options(
  bregr.save_model = TRUE,
  bregr.path = "./bregr_models"
)
```


With parallel computation:

```{r}
system.time(
  br_pipeline(
    data2,
    y = c("OS.time", "OS"),
    x = gene_names, 
    method = "coxph",
    run_parallel = 40
  ) |>
    suppressWarnings()
)
```


Without parallel computation:

```{r}
system.time(
  br_pipeline(
    data2,
    y = c("OS.time", "OS"),
    x = gene_names, 
    method = "coxph"
  ) |>
    suppressWarnings()
)
```


